import Link from "next/link";
import { notFound } from "next/navigation";
import { getMockPatient } from "@/lib/data/mock-patients";

const Field=({id,label,placeholder,step}:{id:string;label:string;placeholder:string;step?:string})=><div className="field"><label htmlFor={id}>{label}</label><input id={id} type="number" step={step} placeholder={placeholder}/></div>;

export default async function NewAssessmentPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params; const patient=getMockPatient(id); if(!patient) notFound();
  return <main className="shell"><Link href={`/patients/${patient.id}`} className="back">← {patient.name}</Link><h1>Nova avaliação</h1><div className="notice" style={{marginBottom:22}}>Formulário visual do MVP. Nesta etapa ele ainda não persiste dados; isso será conectado ao banco após validarmos o fluxo com pacientes fictícios.</div><form className="card"><h2 className="section-title" style={{marginTop:0}}>Antropometria</h2><div className="form-grid"><Field id="weight" label="Peso" placeholder="kg" step="0.1"/><Field id="waist" label="Circunferência abdominal" placeholder="cm" step="0.1"/></div><h2 className="section-title">Pressão arterial</h2><div className="form-grid"><Field id="office-sbp" label="PAS consultório" placeholder="mmHg"/><Field id="office-dbp" label="PAD consultório" placeholder="mmHg"/><Field id="home-sbp" label="PAS residencial média" placeholder="mmHg"/><Field id="home-dbp" label="PAD residencial média" placeholder="mmHg"/></div><h2 className="section-title">Perfil lipídico</h2><div className="form-grid"><Field id="tc" label="Colesterol total" placeholder="mg/dL"/><Field id="ldl" label="LDL-c" placeholder="mg/dL"/><Field id="hdl" label="HDL-c" placeholder="mg/dL"/><Field id="tg" label="Triglicérides" placeholder="mg/dL"/><Field id="apob" label="ApoB" placeholder="mg/dL"/><Field id="lpa" label="Lp(a)" placeholder="valor"/></div><h2 className="section-title">Metabólico e renal</h2><div className="form-grid"><Field id="glucose" label="Glicemia" placeholder="mg/dL"/><Field id="hba1c" label="HbA1c" placeholder="%" step="0.1"/><Field id="creatinine" label="Creatinina" placeholder="mg/dL" step="0.01"/><Field id="uacr" label="UACR" placeholder="mg/g" step="0.1"/></div><h2 className="section-title">Aterosclerose subclínica</h2><div className="form-grid"><Field id="cac" label="Escore de cálcio" placeholder="Agatston"/><div className="field"><label htmlFor="cac-date">Data do CAC</label><input id="cac-date" type="date"/></div></div><div style={{marginTop:26}}><button className="button" type="button">Salvar e calcular</button></div></form></main>;
}
